# Generated by Django 3.1.6 on 2021-08-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=30)),
                ('station', models.CharField(max_length=30)),
                ('transport', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consignees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee', models.CharField(max_length=30)),
                ('party_consignee', models.PositiveIntegerField(blank=True, null=True)),
                ('station', models.CharField(max_length=30)),
                ('transport', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeorders.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Groups',
            fields=[
                ('group_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('group_des', models.CharField(blank=True, max_length=100, null=True)),
                ('group_type', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.PositiveIntegerField()),
                ('orderdate', models.DateField()),
                ('item_id', models.PositiveIntegerField()),
                ('item_des', models.CharField(blank=True, max_length=50, null=True)),
                ('item_price', models.FloatField()),
                ('qty', models.FloatField()),
                ('unit', models.CharField(choices=[('Bag', 'Bag'), ('Box', 'Box'), ('Dozen', 'Dozen'), ('Gms.', 'Gms.'), ('Kgs.', 'Kgs.'), ('Meter', 'Meter'), ('Pcs.', 'Pcs.'), ('Roll', 'Roll'), ('Liter', 'Liter'), ('Carton', 'Carton')], default='Carton', max_length=30)),
                ('sent_cancel', models.FloatField(blank=True, default=0, null=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('sent_trs_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('consignees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeorders.consignees')),
            ],
        ),
        migrations.CreateModel(
            name='Sentorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Sent', 'Sent'), ('Transfer To', 'Transfer To Consignee')], default='Sent', max_length=30, null=True)),
                ('consignee_id', models.PositiveIntegerField(blank=True, null=True)),
                ('by', models.CharField(blank=True, choices=[('ByUs', 'ByUs'), ('ByParty', 'ByParty')], default='ByUs', max_length=30, null=True)),
                ('order_trs_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docket_number', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeorders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeorders.item_groups')),
            ],
        ),
    ]
