# Generated by Django 3.1.6 on 2021-06-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=30)),
                ('station', models.CharField(max_length=30)),
                ('transport', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consignees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee', models.CharField(max_length=30)),
                ('station', models.CharField(max_length=30)),
                ('transport', models.CharField(max_length=30)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeorders.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateField()),
                ('item_id', models.PositiveIntegerField()),
                ('item_price', models.FloatField()),
                ('qty', models.FloatField(default=1)),
                ('unit', models.CharField(choices=[('Bag', 'Bag'), ('Box', 'Box'), ('Dozen', 'Dozen'), ('Gms.', 'Gms.'), ('Kgs.', 'Kgs.'), ('Meter', 'Meter'), ('Pcs.', 'Pcs.'), ('Roll', 'Roll'), ('Liter', 'Liter'), ('Carton', 'Carton')], default='Carton', max_length=30)),
                ('sent_cancel', models.FloatField(blank=True, default=0, null=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('consignees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeorders.consignees')),
            ],
        ),
        migrations.CreateModel(
            name='Sentorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty', models.FloatField(default=1)),
                ('status', models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Transfer To Consignee', 'Transfer To Consignee')], default='Delivered', max_length=30, null=True)),
                ('consignee_id', models.PositiveIntegerField(blank=True, null=True)),
                ('by', models.CharField(blank=True, choices=[('ByUs', 'ByUs'), ('ByParty', 'ByParty')], default='ByUs', max_length=30, null=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeorders.orders')),
            ],
        ),
    ]
