# Generated by Django 3.1.7 on 2021-05-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consignees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee', models.CharField(max_length=30)),
                ('station', models.CharField(max_length=30)),
                ('trasport', models.CharField(max_length=30)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeorders.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateField()),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.FloatField(default=10.0)),
                ('ordered_cartons', models.PositiveIntegerField(default=1)),
                ('sent_cancel', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('balance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('consignees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeorders.consignees')),
            ],
        ),
        migrations.CreateModel(
            name='Sentorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cartons', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Delivered', max_length=30, null=True)),
                ('by', models.CharField(blank=True, choices=[('ByUs', 'ByUs'), ('ByParty', 'ByParty')], default='ByUs', max_length=30, null=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeorders.orders')),
            ],
        ),
    ]
