# Generated by Django 3.1.7 on 2021-05-23 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='trasport',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
