# Generated by Django 3.1.6 on 2021-04-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignees',
            name='orderdate',
            field=models.DateTimeField(),
        ),
    ]
