# Generated by Django 3.1.6 on 2021-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentorder',
            name='consignee_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Transfer To Consignee', 'Transfer To Consignee')], default='Delivered', max_length=30, null=True),
        ),
    ]
