# Generated by Django 3.1.7 on 2021-05-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0002_clients_trasport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='trasport',
            new_name='transport',
        ),
        migrations.RenameField(
            model_name='consignees',
            old_name='trasport',
            new_name='transport',
        ),
    ]
