# Generated by Django 3.1.6 on 2021-06-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0002_auto_20210612_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_price',
            field=models.FloatField(),
        ),
    ]
