# Generated by Django 3.2.3 on 2021-07-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0002_auto_20210708_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Groups',
            fields=[
                ('group_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('group_des', models.CharField(max_length=100)),
            ],
        ),
    ]
