# Generated by Django 3.1.6 on 2021-04-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0002_auto_20210428_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignees',
            name='orderdate',
            field=models.DateField(),
        ),
    ]
