# Generated by Django 3.1.6 on 2021-08-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0002_orders_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='per',
            field=models.CharField(choices=[('Bag', 'Bag'), ('Box', 'Box'), ('Dozen', 'Dozen'), ('Gms.', 'Gms.'), ('Kgs.', 'Kgs.'), ('Meter', 'Meter'), ('Pcs.', 'Pcs.'), ('Roll', 'Roll'), ('Liter', 'Liter'), ('Carton', 'Carton')], default='Kgs.', max_length=30),
        ),
    ]
