# Generated by Django 3.1.7 on 2021-05-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0003_auto_20210523_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='address',
            new_name='station',
        ),
    ]
