# Generated by Django 3.1.6 on 2021-06-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0003_auto_20210625_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_trs_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
