# Generated by Django 3.1.6 on 2021-05-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0003_auto_20210430_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ordered_cartons',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
