# Generated by Django 3.2.3 on 2021-07-12 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0003_item_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='makeorders.item_groups'),
            preserve_default=False,
        ),
    ]
