# Generated by Django 3.2.3 on 2021-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0004_items_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='group_id',
            new_name='item_group',
        ),
        migrations.AddField(
            model_name='item_groups',
            name='group_type',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
