# Generated by Django 3.1.6 on 2021-05-04 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0004_auto_20210502_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignees',
            old_name='shipto',
            new_name='consignee',
        ),
        migrations.RemoveField(
            model_name='consignees',
            name='orderdate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ordercomplete',
        ),
        migrations.AddField(
            model_name='orders',
            name='orderdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentorder',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sentorder',
            name='cancelled_cartons',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
