# Generated by Django 3.1.7 on 2021-05-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0004_auto_20210523_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordered_cartons',
        ),
        migrations.RemoveField(
            model_name='sentorder',
            name='cartons',
        ),
        migrations.AddField(
            model_name='orders',
            name='qty',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='sentorder',
            name='qty',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sent_cancel',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
