# Generated by Django 3.1.6 on 2021-06-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0005_auto_20210629_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentorder',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
