# Generated by Django 3.2.3 on 2021-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0005_auto_20210712_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consignees',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item_groups',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sentorder',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
