# Generated by Django 3.1.6 on 2021-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0005_auto_20210712_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='clients',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consignees',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sentorder',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item_groups',
            name='group_des',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
