# Generated by Django 3.1.7 on 2021-05-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0005_auto_20210527_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='sent_cancel',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
