# Generated by Django 3.1.6 on 2021-05-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0005_auto_20210504_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentorder',
            old_name='sent_cartons',
            new_name='cartons',
        ),
        migrations.RenameField(
            model_name='sentorder',
            old_name='sent_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='sentorder',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='sentorder',
            name='cancelled_cartons',
        ),
        migrations.RemoveField(
            model_name='sentorder',
            name='cancelled_date',
        ),
        migrations.AddField(
            model_name='sentorder',
            name='by',
            field=models.CharField(blank=True, choices=[('ByUs', 'ByUs'), ('ByParty', 'ByParty')], default='ByUs', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sentorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancel', 'Cancel'), ('Sent', 'Sent')], default='Sent', max_length=30, null=True),
        ),
    ]
