# Generated by Django 3.1.6 on 2021-06-29 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0006_auto_20210629_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 29, 17, 40, 9, 689931), null=True),
        ),
        migrations.AlterField(
            model_name='sentorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
