# Generated by Django 3.1.6 on 2021-05-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0006_auto_20210504_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='ordered_cancelled',
            new_name='sent_cancel',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_balance',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ordered_cartons_sent',
        ),
    ]
