# Generated by Django 3.1.7 on 2021-05-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0006_auto_20210527_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='unit',
            field=models.CharField(blank=True, choices=[('Bag', 'Bag'), ('Box', 'Box'), ('Dozen', 'Dozen'), ('Gms.', 'Gms.'), ('Kgs.', 'Kgs.'), ('Meter', 'Meter'), ('Pcs.', 'Pcs.'), ('Roll', 'Roll'), ('Liter', 'Liter'), ('Carton', 'Carton')], default='Carton', max_length=30, null=True),
        ),
    ]
