# Generated by Django 3.2.3 on 2021-08-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0007_sentorder_docket_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_groups',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='items',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item_groups',
            name='group_des',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentorder',
            name='qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sentorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Sent', 'Sent'), ('Transfer To', 'Transfer To Consignee')], default='Sent', max_length=30, null=True),
        ),
    ]
