# Generated by Django 3.1.6 on 2021-05-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0007_auto_20210504_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
