# Generated by Django 3.1.6 on 2021-06-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0008_auto_20210629_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentorder',
            name='order_trs_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
