# Generated by Django 3.1.7 on 2021-05-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0008_auto_20210529_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_price',
            field=models.FloatField(default=0.0),
        ),
    ]
