# Generated by Django 3.1.6 on 2021-06-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0009_sentorder_order_trs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_trs_id',
            new_name='sent_trs_id',
        ),
    ]
