# Generated by Django 3.1.6 on 2021-06-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0010_auto_20210629_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignees',
            name='party_consignee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
