# Generated by Django 3.1.7 on 2021-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0010_auto_20210514_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='item_rate',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
