# Generated by Django 3.1.7 on 2021-05-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0011_auto_20210522_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item_rate',
            new_name='item_price',
        ),
    ]
