# Generated by Django 3.1.7 on 2021-05-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0012_auto_20210522_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_price',
            field=models.FloatField(default=10.0),
        ),
    ]
